### ISSUE TITLE
[Enhancement] Update prerequisite checker to "not download helm if helm is in $PATH"

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#397] opened 2020-09-17 19:37 UTC
[Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/397#issuecomment-694457184)

### [Enhancement] Update Helm_deploy workload test "do not download helm if it’s in $PATH"

**Short description:** 
- to update `helm_deploy` workload test
- do not download helm if it’s in $PATH
- related to #69 workload test called `helm_deploy`

What happens now: 
- if the pre-req finds helm in the network function, the test suite will download helm to a tools directory 

What we would like to see instead: 
- if the pre-req finds helm in $PATH, then do not download helm to the tools directory

**Audience:** 
- Service Provider

**Test Category:** 
-  Installable and Upgradeable Tests

**Type of test (static or runtime)**
- Runtime

**Are there any pre-requisites?**
- helm v3+

**Command name:**
- helm_deploy

---

### Implementation Tasks: TBD

**Environment set up tasks:**
- [ ] 

**Upstream tool set up tasks: (conformance suite + upstream tools)**
- [ ]  N/A

**Code implementation tasks:**
- [ ] 

**Documentation tasks:**
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-conformance/blob/master/TEST-CATEGORIES.md) if needed 
- [ ] Update [Pseudo Code md](https://github.com/cncf/cnf-conformance/blob/master/PSEUDO-CODE.md) if needed
- [ ] Update [USAGE md](https://github.com/cncf/cnf-conformance/blob/master/USAGE.md) if needed 
- [ ] Update [installation instructions](https://github.com/cncf/cnf-conformance#installation)  if needed 

### QA tasks

Dev Review: 
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by lixuna** [comment] 2020-09-17 19:39
Acceptance Criteria: building on A/C from #159
---

### Acceptance Criteria for peer review:
--
### Documentation is updated:
- [ ]  Documentation lists new test name
- [ ]  Test Categories md is updated
- [ ]  USAGE md is updated
- [ ]   Installation instructions is updated

###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in Travis CI
- [ ]   As a peer reviewer, check that PR passes Travis CI tests
     - [ ]  if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]  As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]   I expect to see PASSED for the tests


### Update Prerequistite checker
- N/A

### Update example CNFs cnf-conformance.yml, if needed
- [ ] continue, If there is an update to cnf-conformance.yml
- [ ] for each CNF Example
- [ ] Update the example CNF's cnf-conformance.yml to include the new changes
- [ ] Update the example CNF's README if needed
- [ ] Test the example CNF following it's README

### Update yml validator, if needed
- N/A

### When using the test `cnf-conformance volume_hostpath_not_found` command the sample "good" CNF should PASS test successfully:
- [ ]   Run `./cnf-conformance setup`
- [ ]   Run  `./cnf-conformance sample_coredns_setup`
- [ ]   Run  `./cnf-conformance volume_hostpath_not_found`
- [ ]   I expect to see the output and results from the test
- [ ]  I expect to see PASSED for the test. Example:
         - [ ] "✔️ PASSED: hostPath volumes not found [EMOJI]"

### When using the test `crystal spec --tag `volume_hostpath_not_found` command the sample "good" CNF should PASS and the "bad example CNF"  should FAIL test:
- [ ]   Run `crystal spec --tag volume_hostpath_not_found`
- [ ]   I expect to see the output and results from the test
- [ ]  I expect to see "✔️ PASSED: hostPath volumes not found [EMOJI]
- [ ]  I expect to see "❌ FAIL: hostPath volumes found [EMOJI]"

### I would expect the CNF to pass when I run the entire test category suite (`statelessness`)
- [ ]    Follow common steps above
- [ ]    Run  `./cnf-conformance sample_coredns_setup`
- [ ]   Run  `./cnf-conformance statelessness`
- [ ]    I expect to see the output and results from all tests in the test category
- [ ]    I expect to see PASSED for the test and test category 

### I would expect the CNF to pass when I run the entire test suite (`all`)
- [ ]   Follow common steps above
- [ ]    Run  `./cnf-conformance sample_coredns_setup`
- [ ]    Run  `./cnf-conformance all`
- [ ]   I expect to see the output from the test
- [ ]    I expect to see PASSED for the test

### Screenshots of new test and results in the comments
- [ ]  New test should be added to the points file
- [ ]  New test score should be added to the final score
- [ ] I can see a screenshot of the new test in the comments of this ticket

**Comment by lixuna** [comment] 2020-09-17 20:06
### Level of effort in pts: 0,1,2,3,5,8,13,21 -  pts

@denverwilliams 
@wavell 
@williscool
@agentpoyo 
@taylor 
@lixuna

**Comment by agentpoyo** [comment] 2020-09-28 19:32
So checking out `master` branch ( I actually did a git fetch and pull of latest master), seems if I delete everything beyond in ./tools/helm/ but leave the helm directory empty (from original download), the setup and pre-reqs ignore the older version I installed and does not download again until after I delete ./tools/helm entirely. 

I would imagine we want to actually verify the version perhaps and not just check if the ./tools/helm directory is present.

![does_not_download_helm](https://user-images.githubusercontent.com/14348948/94476454-1ee55400-0196-11eb-9174-f42b8cce26ae.png)

After I blew away the tools/helm directory, it downloads helm 3.1.1:

![helm_downloads](https://user-images.githubusercontent.com/14348948/94477421-7d5f0200-0197-11eb-8e34-0328df08fa34.png)

**Comment by agentpoyo** [comment] 2020-09-28 19:36
### The `cnf-conformance setup` should install helm if the version in the System is not new enough
- [ ] I should see helm is installed in the System with the version
   - [ ] Optional: message in output can say system version is too old
- [ ] I should see a message saying helm is installed locally with a version that meets the CNF Conformance requiremnts (eg. greater than version 3)
- [ ] The output says, “Setup complete."

Using version 2.x, It does not tell me my version is too old. I also do not see requirements message, it just proceeds int downloaded after saying all pre-reqs are met (despite me having Helm 2.16.12 installed locally).

@wavell @denverwilliams @taylor

**Comment by agentpoyo** [comment] 2020-09-28 19:40
Also, if local helm is found on system, seems setup still downloads helm (with version that meets requirements):

![helm_downloads_despite_3 1 1_being_installed](https://user-images.githubusercontent.com/14348948/94478188-8e5c4300-0198-11eb-9068-a7b15e0e8a52.png)

**Comment by agentpoyo** [comment] 2020-09-28 19:43
If helm is not installed or found, prereqs makes note of helm but still says `All prerequisites found.`

![helm_not_found_but](https://user-images.githubusercontent.com/14348948/94478486-f3b03400-0198-11eb-84f6-cba24be9bf15.png)

**Comment by agentpoyo** [comment] 2020-09-28 19:45
After running setup, it now displays the version information:

![helm_downloaded_with_version](https://user-images.githubusercontent.com/14348948/94478736-4b4e9f80-0199-11eb-984b-1815176b69b9.png)

**Comment by agentpoyo** [comment] 2020-09-28 22:28
Update: I started peer review thinking this was already merged into master, which it's failing travis CI. So some of my findings might not be valid until travis is fixed and merged.

**Comment by williscool** [comment] 2020-09-29 07:48
@agentpoyo pretty sure most recent failures on master have all been #414

**Comment by agentpoyo** [comment] 2020-09-29 13:44
> @agentpoyo pretty sure most recent failures on master have all been #414

These findings are not big but I did point out that if there's a empty ./tools/helm directory, `setup` completely ignores downloading helm if you have older version, no version, etc. It thinks it already has helm installed in the tools/ for use. I only happen to hit this snag cause I had run a previous setup before doing another git pull and thought by wiping out ./tools/helm/* would do the trick when peer reviewing helm versions and downloading of helm.

**Comment by williscool** [comment] 2020-10-07 16:44
Wrote a version of curl_install_tester dockerfile to test this

you can just take master 

https://github.com/cncf/cnf-conformance/blob/master/tools/curl_install_tester_docker_setup/Dockerfile

and add 

```
 COPY cnf-conformance .
```

to the bottom then

```
cp cnf-conformance tools/curl_install_tester_docker_setup/

after you build the binary 


inside of that docker container


``` bash

☺ ➔  docker run --rm -it --entrypoint /bin/bash curl_install_tester
root@24432f28a3ae:/test_workspace# ./cnf-conformance prereqs
Global helm found. Version: v3.2.4
Local helm found. Version: v3.2.4
Global wget found. Version: 1.20.3
No Local wget version found
Global curl found. Version: 7.68.0
No Local curl version found
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Global kubectl found. Version: 1.18
No Local kubectl version found
Global git found. Version: 2.25.1
No Local git version found
All prerequisites found.
root@24432f28a3ae:/test_workspace#
Global helm found. Version: v3.2.4
Local helm found. Version: v3.2.4
Global wget found. Version: 1.20.3
No Local wget version found
Global curl found. Version: 7.68.0
No Local curl version found
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Global kubectl found. Version: 1.18
No Local kubectl version found
Global git found. Version: 2.25.1
No Local git version found
All prerequisites found.
root@24432f28a3ae:/test_workspace# ls
cnf-conformance  results


```


I get taht local helm is installed even though as you can see from the `ls` `setup`  has not been run so the tools folder doesn't exist yet.

I think this is realated to changes for `CNFSingleton.helm` 

@wavell

**Comment by agentpoyo** [comment] 2020-10-12 21:58
Latest stable binary release getting unexpected results if helm not installed locally:

Following curl installation method, here is the version output:
```
vagrant@ubuntu-bionic:~$ cnf-conformance version
CNF Conformance version: v0.8.5
```
Running `cnf-conformance prereqs` finds helm not installed but errors out immediately:
![helm_prereqs_1](https://user-images.githubusercontent.com/14348948/95793590-8e396880-0cab-11eb-9798-00b5f0bb316b.png)

Running `cnf-conformance setup` results in same output as prereqs:
![helm_prereqs_2](https://user-images.githubusercontent.com/14348948/95793647-af9a5480-0cab-11eb-877b-28a6fc1175af.png)

Moving helm v3.1.1 back into my PATH gets the following results.

`which helm` and the version info:
![helm_prereqs_2 5](https://user-images.githubusercontent.com/14348948/95793703-c5a81500-0cab-11eb-9a59-075ce7d63eb1.png)

Now prereqs looks good:
![helm_prereqs_3](https://user-images.githubusercontent.com/14348948/95793733-d8224e80-0cab-11eb-95d8-74512712c0d5.png)

And `setup` runs without issues:
![helm_prereqs_4](https://user-images.githubusercontent.com/14348948/95793749-e2444d00-0cab-11eb-8d20-d28b7b0ce926.png)

And helm is not downloaded since it's found locally:
```
vagrant@ubuntu-bionic:~/tools$ pwd
/home/vagrant/tools
vagrant@ubuntu-bionic:~/tools$ ls
sonobuoy
```

**Comment by agentpoyo** [comment] 2020-10-12 22:05
Binary install and then running `cnf_setup` results are, prereqs bombs out but running cnf_setup then downloads helm:

```
vagrant@ubuntu-bionic:~$ sudo mv /usr/local/bin/helm /tmp

vagrant@ubuntu-bionic:~$ cnf-conformance prereqs
Global helm found. Version: 
Local helm found. Version: 
Helm not found

    Installation instructions for Helm can be found here: https://helm.sh/docs/intro/install

    To install helm on Linux use:
    sudo snap install helm --classic
    
../../usr/share/crystal/src/crystal/system/unix/process.cr:225:34 in 'raise_exception_from_errno'
../../usr/share/crystal/src/array.cr:1558:5 in 'spawn'
../../usr/share/crystal/src/process.cr:230:21 in 'new:output:error'
../../workspace/src/tasks/utils/cnf_manager.cr:271:14 in '->'
../../workspace/lib/sam/src/sam.cr:43:5 in '__crystal_main'
../../usr/share/crystal/src/crystal/main.cr:105:5 in 'main'
src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
Error executing process: '/home/vagrant/tools/helm/linux-amd64/helm': No such file or directory

vagrant@ubuntu-bionic:~$ cnf-conformance cnf_setup
Successfully created directories for cnf-conformance
--2020-10-12 22:00:16--  https://get.helm.sh/helm-v3.1.1-linux-amd64.tar.gz
Resolving get.helm.sh (get.helm.sh)... 152.195.19.97, 2606:2800:11f:1cb7:261b:1f9c:2074:3c
Connecting to get.helm.sh (get.helm.sh)|152.195.19.97|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12270615 (12M) [application/x-tar]
Saving to: ‘/home/vagrant/tools/helm/helm-v3.1.1-linux-amd64.tar.gz’

/home/vagrant/tools/helm/helm- 100%[==================================================>]  11.70M  6.43MB/s    in 1.8s    

2020-10-12 22:00:19 (6.43 MB/s) - ‘/home/vagrant/tools/helm/helm-v3.1.1-linux-amd64.tar.gz’ saved [12270615/12270615]

Error: You must supply either cnf-config or cnf-path
```

So our install guide says to run `cnf-conformance setup` after downloading the binary via curl but it appears if a user does not have helm installed, it will error out unless they go back and run `cnf_setup` prior to `prereqs` and or `setup`.

**Comment by agentpoyo** [comment] 2020-10-20 17:55
Much cleaner now after updates. prereqs doesn't bomb out if helm is found and then not found, with proper warnings:

![helm_397_updates](https://user-images.githubusercontent.com/14348948/96625196-77120080-12d3-11eb-9ccd-9e22cd49429b.png)

**Comment by agentpoyo** [comment] 2020-10-20 17:58
Seems I still need to run cnf_setup to make cnf-conformance download helm when it's not found, is this expected behavior? The AC jump straight to `setup` should download. @wavell @denverwilliams 

![cnf_setup_helm_not_found](https://user-images.githubusercontent.com/14348948/96625531-ebe53a80-12d3-11eb-9212-9529a857fcb2.png)

**Comment by agentpoyo** [comment] 2020-10-20 18:04
If I have older version of helm installed, seems it still bombs out running prereqs:

![older_helm_bombs](https://user-images.githubusercontent.com/14348948/96626182-c147b180-12d4-11eb-817f-c2a31349cbe0.png)

**Comment by agentpoyo** [comment] 2020-10-21 20:59
Updates look good when it finds older version of helm installed:

![older_version_helm](https://user-images.githubusercontent.com/14348948/96786736-4c4ca880-13b6-11eb-9291-40477de484d5.png)

**Comment by agentpoyo** [comment] 2020-10-21 21:00
Setup downloads newer helm if version < 3.1.1:

![older_version_helm_setup](https://user-images.githubusercontent.com/14348948/96786891-80c06480-13b6-11eb-93c6-9a5645812f63.png)

**Closed** 2020-10-22 17:54 UTC
Labels: 3 pts, enhancement, sprint16, sprint17, sprint18, workload
