### ISSUE TITLE
[BUG] Latest Binary Error - Curl Installation Method  for cnf-conformance v0.8.4

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-conformance#398] opened 2020-09-17 21:41 UTC
**Describe the bug**
Installing cnf-conformance via curl installation method results in errors when passing any argument with latest binary v0.8.4

**To Reproduce**
1. Follow the curl installation method from the [README.md](https://github.com/cncf/cnf-conformance/blob/v0.8.4/README.md)
2. `source <(curl https://raw.githubusercontent.com/cncf/cnf-conformance/master/curl_install.sh)`
3. Verify cnf-conformance in path: `which cnf-conformance` which should output: `$HOME/.cnf-conformance/cnf-conformance`
4. Now run `cnf-conformance setup` which should install prereqs, etc. 

**Expected behavior**
`cnf-conformance` should install pre-reqs and setup the cnf-conformance environment.

Instead it errors out with the following:

```
vagrant@ubuntu-bionic:~$ cnf-conformance setup
Unhandled exception: Error opening file with mode 'r': './tools/reboot_daemon/manifest.yml': No such file or directory (File::NotFoundError)
  from ../../usr/share/crystal/src/int.cr:1091:11 in 'new'
  from ../../usr/share/crystal/src/file.cr:627:12 in 'read'
  from ../../usr/share/crystal/src/pointer.cr:437:13 in '???'
  from ../../usr/share/crystal/src/primitives.cr:255:3 in '__crystal_once'
  from ../../workspace/src/tasks/utils/utils.cr:28:1 in '__crystal_main'
  from ../../usr/share/crystal/src/crystal/main.cr:105:5 in 'main'
  from src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
```

Passing version argument results in the same error:

```
$ cnf-conformance version
Unhandled exception: Error opening file with mode 'r': './tools/reboot_daemon/manifest.yml': No such file or directory (File::NotFoundError)
  from ../../usr/share/crystal/src/int.cr:1091:11 in 'new'
  from ../../usr/share/crystal/src/file.cr:627:12 in 'read'
  from ../../usr/share/crystal/src/pointer.cr:437:13 in '???'
  from ../../usr/share/crystal/src/primitives.cr:255:3 in '__crystal_once'
  from ../../workspace/src/tasks/utils/utils.cr:28:1 in '__crystal_main'
  from ../../usr/share/crystal/src/crystal/main.cr:105:5 in 'main'
  from src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
```

**Screenshots**
![error_cnf-conf-binary_v8 0 4](https://user-images.githubusercontent.com/14348948/93531055-3d309180-f904-11ea-9a94-a7316fd19f89.png)

**Workstation (please complete the following information):**
 - OS Linux
 - Distro Ubuntu
 - Version 18.04
 - Architecture x86

**Comment by williscool** [comment] 2020-09-25 04:15
pretty sure this is a dupe of #369

**Comment by williscool** [comment] 2020-09-25 05:27
not an exact dup but broken for a similar reason.

We all dev with the source at hand and at times subtily introduce dependencies from having the full source in teh directory we are working with binary.

I'm considering plotting out some tests that will build the binary , run the setup command, install a simple cnf, and run one quick test to try to make sure we aren't breaking being able to use the static bin without the rest of the source in the same directory

**Comment by nupejosh** [comment] 2020-09-29 22:25
![Screen Shot 2020-09-29 at 5 21 41 PM](https://user-images.githubusercontent.com/3164983/94622804-7bb93b00-0278-11eb-9651-7dd664ec2439.png)

I got this to work locally by following your steps to reproduce @agentpoyo. However at the moment we still need to push a new release in order to test with a pulled version from source. The push @wavell made is good to go

**Comment by wavell** [comment] 2020-10-04 18:52
The actual curl binary is fixed in this release:

https://github.com/cncf/cnf-conformance/releases/tag/v0.8.5

**Closed** 2020-10-12 16:08 UTC
Labels: 2 pts, bug, sprint16
